Repository kfmp/sm4U, pull requests merged in 2024-07, with the labels that each got.

#3 공통 레이아웃을 구현한다.
  index.html
  public/images/favicon.png
  public/images/logo.svg
  public/images/profile.png
  src/components/common/common.css
  src/components/common/common.js
  src/css/style.css
  src/index.js
Labels: ✨ Feature, 🎨 Html&css

#10 공통 레이아웃 클래스명을 수정한다.
  src/components/common/common.css
  src/components/common/common.js
Labels: 🎨 Html&css, 🔨 Refactor

#14 메인 페이지 UI를 구현한다.
  src/components/common/common.css
  src/pages/home/graph.js
  src/pages/home/home.css
  src/pages/home/home.html
Labels: ✨ Feature, 🎨 Html&css

#16 Feat/login
  db.json
  public/images/login-logo.svg
  src/components/common/common.js
  src/components/common/reset.css
  src/pages/login/css/login.css
  src/pages/login/login.html
  src/pages/login/loginInsepct.html
  src/pages/test.html
Labels: ✨ Feature

#19 Feat/pay document [#8]
  public/images/sitemap-solid.svg
  src/pages/home/home.css
  src/pages/pay-document/paycheck-resolution.css
  src/pages/pay-document/paycheck-resolution.html
  src/pages/pay-document/paydocument.css
  src/pages/pay-document/paydocument.html
  src/pages/pay-document/paydocumentClickup.css
  src/pages/pay-document/paydocumentClickup.html
  src/pages/sang-hank/userDetailModle.css
  src/pages/sang-hank/userDetailModle.html
Labels: ✨ Feature, 🎨 Html&css

#23 분리된 각각의 페이지를 통합한다.
  index.html
  json/user.json
  package-lock.json
  package.json
  public/images/admin1-profile.jpeg
  src/components/common/common.css
  src/components/common/common.js
  src/index.js
  src/pages/home/home.html
  src/pages/login/login.css
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/login/loginInsepct.html
  src/pages/pay-document/paydocument.html
  src/pages/salary-management/salary-management-foreach.css
  src/pages/salary-management/salary-management-foreach.html
  src/pages/salary-management/userDetailModle.css
  src/pages/salary-management/userDetailModle.html
  src/pages/salary-management/working-time-management.css
  src/pages/salary-management/working-time-management.html
  src/pages/salary_setting/salary_setting.html
  src/pages/test.html
Labels: 🔨 Refactor

#26 Feat/salary setting
  db.json
  json/tax_free_items.json
  package.json
  src/pages/salary_setting/salary_setting.html
  src/pages/salary_setting/salary_setting.js
Labels: 📬 API, ✨ Feature

#27 급여 대장
  db.json
  src/pages/pay-document/paydocument.css
  src/pages/pay-document/paydocument.html
  src/pages/pay-document/paydocument.js
Labels: ✨ Feature, 🎨 Html&css

#28 Feat/set payroll
  db.json
  package-lock.json
  public/images/search.svg
  src/components/common/common.js
  src/pages/salary-management/bonusesDocument.css
  src/pages/salary-management/bonusesDocument.html
  src/pages/salary-management/bonusesDocument.js
  src/pages/salary-management/mini.js
  src/pages/salary-management/miniTree.css
  src/pages/salary-management/miniTree.html
  src/pages/salary-management/salary-management-foreach.css
  src/pages/salary-management/salary-management-foreach.html
  src/pages/salary-management/salary-management-foreach.js
  src/pages/salary-management/testTree.css
  src/pages/salary-management/testTree.html
  src/pages/salary-management/userDetailModle.css
  src/pages/salary-management/userDetailModle.html
  src/pages/salary-management/userDetailModle.js
Labels: ✨ Feature, 🎨 Html&css

#31 전자 결재 기능을 구현한다.
  src/pages/pay-document/paycheck-resolution.css
  src/pages/pay-document/paycheck-resolution.html
  src/pages/pay-document/paycheck-resolution.js
  src/pages/salary-management/working-time-management.css
  src/pages/salary-management/working-time-management.html
Labels: ✨ Feature, 🎨 Html&css

#33 chore: 시계 새로고침 오류 수정 (#32)
  json/aa.txt
  src/components/common/common.js
Labels: 🐞 BugFix, 🔨 Refactor

#34 feat: 최종전 시뮬레이션
  db.json
  json/tax_free_items.json
  src/pages/home/home.html
  src/pages/pay-document/paycheck-resolution.js
  src/pages/pay-document/paydocument.js
  src/pages/salary-management/salary-management-foreach.html
  src/pages/salary-management/working-time-management.html
  src/pages/salary_setting/salary_setting.html
  src/pages/salary_setting/salary_setting.js
Labels: ✨ Feature

#35 jsdoc 메서드 주석 작성
  src/pages/pay-document/paycheck-resolution.js
Labels: 🥰 Accessibility

#36 Init/dummy
  db.json
  src/pages/pay-document/paycheck-resolution.js
  src/pages/pay-document/paydocument.js
Labels: ✨ Feature

#37 Init/dummy
  db.json
  src/pages/salary-management/bonusesDocument.js
  src/pages/salary-management/salary-management-foreach.js
Labels: ✨ Feature
